apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-web-app
  namespace: atlas
spec:
  selector:
    matchLabels:
      app: java-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-web-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node3

      containers:
      - name: java-web-app
        image: IMAGE_VERSION
        resources: {} 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # envFrom:
        #   - configMapRef:
        #       name: configmap-java-web-app
        env:
          - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
            value: "THIS_STRING_IS_REPLACED_DURING_BUILD"
      # imagePullSecrets:
      # - name: regcred-java-web-app-dev
      